var tr = 9;
var td = 9;
var latticetr = { domContent : "" }
var latticetd = { domContent : "" }
var tdContent = { domContent : "" }
// var content = {domContent : ""}
// var contenthtml = "";
var timeStop = null;
var latticeArr = [];
var maxLei = 6;
// var spanDom = { domContent : "" }
var lei = { x : 0,y : 0, domContent: ""}